// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc_chat {

static const char* chatting_method_names[] = {
  "/grpc_chat.chatting/sendMessage",
};

std::unique_ptr< chatting::Stub> chatting::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< chatting::Stub> stub(new chatting::Stub(channel, options));
  return stub;
}

chatting::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sendMessage_(chatting_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status chatting::Stub::sendMessage(::grpc::ClientContext* context, const ::grpc_chat::Request& request, ::grpc_chat::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_chat::Request, ::grpc_chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_sendMessage_, context, request, response);
}

void chatting::Stub::experimental_async::sendMessage(::grpc::ClientContext* context, const ::grpc_chat::Request* request, ::grpc_chat::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_chat::Request, ::grpc_chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendMessage_, context, request, response, std::move(f));
}

void chatting::Stub::experimental_async::sendMessage(::grpc::ClientContext* context, const ::grpc_chat::Request* request, ::grpc_chat::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_chat::Response>* chatting::Stub::PrepareAsyncsendMessageRaw(::grpc::ClientContext* context, const ::grpc_chat::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_chat::Response, ::grpc_chat::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_sendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_chat::Response>* chatting::Stub::AsyncsendMessageRaw(::grpc::ClientContext* context, const ::grpc_chat::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

chatting::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      chatting_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< chatting::Service, ::grpc_chat::Request, ::grpc_chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](chatting::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_chat::Request* req,
             ::grpc_chat::Response* resp) {
               return service->sendMessage(ctx, req, resp);
             }, this)));
}

chatting::Service::~Service() {
}

::grpc::Status chatting::Service::sendMessage(::grpc::ServerContext* context, const ::grpc_chat::Request* request, ::grpc_chat::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_chat

