CREATE DATABASE IF NOT EXISTS grpcdata;
USE grpcdata;

CREATE TABLE IF NOT EXISTS chatdata
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  posttime DATETIME NOT NULL,
  PRIMARY KEY(id)
)DEFAULT CHARACTER
  SET=utf8;